import numpy as np

from day_08.main import create_matrix_from_text, build_antenna_points, process_antenna_points


def test_day_08_task_01():
    example = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

    result = """......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....A.....
...#........
#......#....
........A...
.........A..
..........#.
..........#."""

    matrix = create_matrix_from_text(example)
    antenna_points = build_antenna_points(matrix)
    
    result_matrix, number_of_unique_locations = process_antenna_points(matrix, antenna_points)
    assert np.array_equal(result_matrix, create_matrix_from_text(result))
    assert number_of_unique_locations == 14